#!/bin/sh

# From: https://github.com/caarlos0/dotfiles/blob/4fa273aed9245118fa5f6c5819537aa7b0fde76e/modules/ssh/rc
# License: MIT

# https://blog.testdouble.com/posts/2016-11-18-reconciling-tmux-and-ssh-agent-forwarding/
# Fix SSH auth socket location so agent forwarding works with tmux
if test "$SSH_AUTH_SOCK" ; then
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
