section: screens
    galactica:
    matic:
end

section: links
    galactica:
        right = matic
    matic:
        left = galactica
end

section: options
    keystroke(super+shift+left) = switchInDirection(left)
    keystroke(super+shift+right) = switchInDirection(right)
end
