core:
  trash:
    strategy: auto
    home_fallback: true
    forbidden_paths:
      - "$HOME/.local/share/Trash"
      - "$HOME/.trash"
      - "$XDG_DATA_HOME/Trash"
      - "/tmp/Trash"
      - "/var/tmp/Trash"
      - "$HOME/.gomi"
      - "/"
      - "/etc"
      - "/usr"
      - "/var"
      - "/bin"
      - "/sbin"
      - "/lib"
      - "/lib64"
  restore:
    confirm: false
    verbose: true
  permanent_delete:
    enable: false
ui:
  density: spacious
  preview:
    syntax_highlight: true
    colorscheme: dracula
    directory_command: ls -F -A --color=always
  style:
    list_view:
      cursor: "#BD93F9"
      selected: "#50FA7B"
      filter_match: "#FFB86C"
      filter_prompt: "#8BE9FD"
      indent_on_select: false
    detail_view:
      border: "#6272A4"
      info_pane:
        deleted_from:
          fg: "#F8F8F2"
          bg: "#282A36"
        deleted_at:
          fg: "#F8F8F2"
          bg: "#282A36"
      preview_pane:
        border: "#44475A"
        size:
          fg: "#F8F8F2"
          bg: "#44475A"
        scroll:
          fg: "#F8F8F2"
          bg: "#44475A"
    deletion_dialog: "#FF79C6"
  exit_message: bye!
  paginator_type: dots
history:
  include:
    within_days: 100
  exclude:
    files:
      - .DS_Store
    patterns:
      - "^\\..*"
    globs:
      - "*.jpg"
    size:
      min: ""
      max: 10GB
logging:
  enabled: false
  level: info
  rotation:
    max_size: 10MB
    max_files: 3
