alias ga='git  add'
alias gb='git  branch'
alias gc='git  commit'
alias gd='git  diff'
alias gf='git  fetch'
alias gg='git  grep'
alias gl='git  log'
alias gm='git  merge'
alias go='git  checkout'
alias gp='git  pull'
alias gs='git  status'
alias gw='git  whatchanged'
alias gaa='git  add --all'
alias gap='git  add --patch'
alias gau='git  add --update'
alias gbm='git  branch --merged'
alias gbnm='git  branch --no-merged'
alias gbed='git  branch --edit-description'
alias gbv='git  branch --verbose'
alias gbvv='git  branch --verbose --verbose'
alias gca='git  commit --amend'
alias gcam='git  commit --amend --message'
alias gcane='git  commit --amend --no-edit'
alias gcaa='git  commit --amend --all'
alias gcaam='git  commit --amend --all --message'
alias gcaane='git  commit --amend --all --no-edit'
alias gci='git  commit --interactive'
alias gcm='git  commit --message'
alias gco='git  checkout'
alias gcong='git  checkout --no-guess'
alias gcob='git  checkout -b'
alias gcp='git  cherry-pick'
alias gcpa='git  cherry-pick --abort'
alias gcpc='git  cherry-pick --continue'
alias gcpn='git  cherry-pick --no-commit'
alias gcpnx='git  cherry-pick --no-commit -x'
alias gdc='git  diff --cached'
alias gds='git  diff --staged'
alias gdw='git  diff --word-diff'
alias gdd='git  diff-deep'
alias gfa='git  fetch --all'
alias gfav='git  fetch --all --verbose'
alias gfap='git  fetch --all --prune'
alias ggn='git  grep --line-number'
alias ggg='git  grep-group'
alias glg='git  log --graph'
alias glo='git  log --oneline'
alias glor='git  log --oneline --reverse'
alias glp='git  log --patch'
alias glfp='git  log --first-parent'
alias glto='git  log --topo-order'
alias gll='git  log-list'
alias glll='git  log-list-long'
alias gls='git  ls-files'
alias glsd='git  ls-files --debug'
alias glsfn='git  ls-files --full-name'
alias glsio='git  ls-files --ignored --others --exclude-standard'
alias gma='git  merge --abort'
alias gmc='git  merge --continue'
alias gmncnf='git  merge --no-commit --no-ff'
alias gpf='git  pull --ff-only'
alias gpr='git  pull --rebase'
alias gprp='git  pull --rebase=preserve'
alias grb='git  rebase'
alias grba='git  rebase --abort'
alias grbc='git  rebase --continue'
alias grbs='git  rebase --skip'
alias grbi='git  rebase --interactive'
alias grl='git  reflog'
alias grr='git  remote'
alias grrs='git  remote show'
alias grru='git  remote update'
alias grrp='git  remote prune'
alias grv='git  revert'
alias grvnc='git  revert --no-commit'
alias gsb='git  show-branch'
alias gsm='git  submodule'
alias gsmi='git  submodule init'
alias gsma='git  submodule add'
alias gsms='git  submodule sync'
alias gsmu='git  submodule update'
alias gsmui='git  submodule update --init'
alias gsmuir='git  submodule update --init --recursive'
alias gss='git  status --short'
alias gssb='git  status --short --branch'
alias glast-tag='git  describe --tags --abbrev=0'
alias gdiff-changes='git  diff --name-status -r'
alias gdiff-stat='git  diff --stat --ignore-space-change -r'
alias gdiff-staged='git  diff --cached'
alias gdiff-deep='git  diff --check --dirstat --find-copies --find-renames --histogram --color'
alias ggrep-group='git  grep --break --heading --line-number --color'
alias gorphans='git  fsck --full'
alias glog-fresh='git  log ORIG_HEAD.. --stat --no-merges'
alias glog-graph='git  log --graph --all --oneline --decorate'
alias glog-date-last='git  log -1 --date-order --format=%cI'
alias glog-1-hour='git  log --since=1-hour-ago'
alias glog-1-day='git  log --since=1-day-ago'
alias glog-1-week='git  log --since=1-week-ago'
alias glog-1-month='git  log --since=1-month-ago'
alias glog-1-year='git  log --since=1-year-ago'
alias glog-refs='git  log --all --graph --decorate --oneline --simplify-by-decoration --no-merges'
alias glog-timeline='git  log --format='\''%h %an %ar - %s'\'''
alias glog-local='git  log --oneline origin..HEAD'
alias glog-fetched='git  log --oneline HEAD..origin/main'
alias grefs-by-date='git  for-each-ref --sort=-committerdate --format='\''%(committerdate:short) %(refname:short) (objectname:short) %(contents:subject)'\'''
alias gwhatis='git  show --no-patch --pretty='\''tformat:%h (%s, %ad)'\'' --date=short'
alias gwho='git  shortlog --summary --numbered --no-merges'
alias giniter='git  init-empty'
alias gcloner='git  clone --recursive'
alias gclone-lean='git  clone --depth 1 --filter=combine:blob:none+tree:0 --no-checkout'
alias gpushy='git  push --force-with-lease'
alias greset-commit='git  reset --soft HEAD~1'
alias greset-commit-hard='git  reset --hard HEAD~1'
alias gundo-commit='git  reset --soft HEAD~1'
alias gundo-commit-hard='git  reset --hard HEAD~1'
alias guncommit='git  reset --soft HEAD~1'
alias gunadd='git  reset HEAD'
alias gdiscard='git  checkout --'
alias gcleaner='git  clean -dff'
alias gcleanest='git  clean -dffx'
alias gassume='git  update-index --assume-unchanged'
alias gunassume='git  update-index --no-assume-unchanged'
alias gbranches='git  branch -a'
alias gtags='git  tag -n1 --list'
alias gstashes='git  stash list'
alias gtop='git  rev-parse --show-toplevel'
alias gdefault-branch='git  config init.defaultBranch'
alias gcurrent-branch='git  rev-parse --abbrev-ref HEAD'
alias grepacker='git  repack -a -d -f --depth=300 --window=300 --window-memory=1g'
alias gtopic-begin='git  topic-start'
alias gtopic-end='git  topic-finish'
alias gcvs-i='git  cvsimport -k -a'
alias gcvs-e='git  cvsexportcommit -u -p'
alias gsvn-b='git  svn branch'
alias gsvn-m='git  merge --squash'
alias gsvn-c='git  svn dcommit'
