abbr -a ga 'git add'
abbr -a gb 'git branch'
abbr -a gc 'git commit'
abbr -a gd 'git diff'
abbr -a gf 'git fetch'
abbr -a gg 'git grep'
abbr -a gl 'git log'
abbr -a gm 'git merge'
abbr -a go 'git checkout'
abbr -a gp 'git pull'
abbr -a gs 'git status'
abbr -a gw 'git whatchanged'
abbr -a gaa 'git add --all'
abbr -a gap 'git add --patch'
abbr -a gau 'git add --update'
abbr -a gbm 'git branch --merged'
abbr -a gbnm 'git branch --no-merged'
abbr -a gbed 'git branch --edit-description'
abbr -a gbv 'git branch --verbose'
abbr -a gbvv 'git branch --verbose --verbose'
abbr -a gca 'git commit --amend'
abbr -a gcam 'git commit --amend --message'
abbr -a gcane 'git commit --amend --no-edit'
abbr -a gcaa 'git commit --amend --all'
abbr -a gcaam 'git commit --amend --all --message'
abbr -a gcaane 'git commit --amend --all --no-edit'
abbr -a gci 'git commit --interactive'
abbr -a gcm 'git commit --message'
abbr -a gco 'git checkout'
abbr -a gcong 'git checkout --no-guess'
abbr -a gcob 'git checkout -b'
abbr -a gcp 'git cherry-pick'
abbr -a gcpa 'git cherry-pick --abort'
abbr -a gcpc 'git cherry-pick --continue'
abbr -a gcpn 'git cherry-pick --no-commit'
abbr -a gcpnx 'git cherry-pick --no-commit -x'
abbr -a gdc 'git diff --cached'
abbr -a gds 'git diff --staged'
abbr -a gdw 'git diff --word-diff'
abbr -a gdd 'git diff-deep'
abbr -a gfa 'git fetch --all'
abbr -a gfav 'git fetch --all --verbose'
abbr -a gfap 'git fetch --all --prune'
abbr -a ggn 'git grep --line-number'
abbr -a ggg 'git grep-group'
abbr -a glg 'git log --graph'
abbr -a glo 'git log --oneline'
abbr -a glor 'git log --oneline --reverse'
abbr -a glp 'git log --patch'
abbr -a glfp 'git log --first-parent'
abbr -a glto 'git log --topo-order'
abbr -a gll 'git log-list'
abbr -a glll 'git log-list-long'
abbr -a gls 'git ls-files'
abbr -a glsd 'git ls-files --debug'
abbr -a glsfn 'git ls-files --full-name'
abbr -a glsio 'git ls-files --ignored --others --exclude-standard'
abbr -a gma 'git merge --abort'
abbr -a gmc 'git merge --continue'
abbr -a gmncnf 'git merge --no-commit --no-ff'
abbr -a gpf 'git pull --ff-only'
abbr -a gpr 'git pull --rebase'
abbr -a gprp 'git pull --rebase=preserve'
abbr -a grb 'git rebase'
abbr -a grba 'git rebase --abort'
abbr -a grbc 'git rebase --continue'
abbr -a grbs 'git rebase --skip'
abbr -a grbi 'git rebase --interactive'
abbr -a grl 'git reflog'
abbr -a grr 'git remote'
abbr -a grrs 'git remote show'
abbr -a grru 'git remote update'
abbr -a grrp 'git remote prune'
abbr -a grv 'git revert'
abbr -a grvnc 'git revert --no-commit'
abbr -a gsb 'git show-branch'
abbr -a gsm 'git submodule'
abbr -a gsmi 'git submodule init'
abbr -a gsma 'git submodule add'
abbr -a gsms 'git submodule sync'
abbr -a gsmu 'git submodule update'
abbr -a gsmui 'git submodule update --init'
abbr -a gsmuir 'git submodule update --init --recursive'
abbr -a gss 'git status --short'
abbr -a gssb 'git status --short --branch'
abbr -a glast-tag 'git describe --tags --abbrev=0'
abbr -a gdiff-changes 'git diff --name-status -r'
abbr -a gdiff-stat 'git diff --stat --ignore-space-change -r'
abbr -a gdiff-staged 'git diff --cached'
abbr -a gdiff-deep 'git diff --check --dirstat --find-copies --find-renames --histogram --color'
abbr -a ggrep-group 'git grep --break --heading --line-number --color'
abbr -a ggrep-ack 'git "\'
abbr -a gorphans 'git fsck --full'
abbr -a glog-fresh 'git log ORIG_HEAD.. --stat --no-merges'
abbr -a glog-graph 'git log --graph --all --oneline --decorate'
abbr -a glog-date-last 'git log -1 --date-order --format=%cI'
abbr -a glog-1-hour 'git log --since=1-hour-ago'
abbr -a glog-1-day 'git log --since=1-day-ago'
abbr -a glog-1-week 'git log --since=1-week-ago'
abbr -a glog-1-month 'git log --since=1-month-ago'
abbr -a glog-1-year 'git log --since=1-year-ago'
abbr -a glog-refs 'git log --all --graph --decorate --oneline --simplify-by-decoration --no-merges'
abbr -a glog-local 'git log --oneline origin..HEAD'
abbr -a glog-fetched 'git log --oneline HEAD..origin/main'
abbr -a g--format 'git oneline \'
abbr -a g--format 'git \"%aE %at\" \'
abbr -a g--since 'git 6-weeks-ago \'
abbr -a gtime_min 'git systime(); time_max = 0; \'
abbr -a gSECONDS_PER_DAY 'git 86400; \'
abbr -a gslot 'git time_to_slot(time); \'
abbr -a gtime_max_add 'git time_max += SECONDS_PER_DAY; \'
abbr -a grow 'git \"\"; \'
abbr -a gslot 'git time_to_slot(time); \'
abbr -a gcount 'git views[item, slot]; \'
abbr -a grow 'git row count_to_char(count); \'
abbr -a gwho 'git shortlog --summary --numbered --no-merges'
abbr -a giniter 'git init-empty'
abbr -a gcloner 'git clone --recursive'
abbr -a gclone-lean 'git clone --depth 1 --filter=combine:blob:none+tree:0 --no-checkout'
abbr -a gpushy 'git push --force-with-lease'
abbr -a greset-commit 'git reset --soft HEAD~1'
abbr -a greset-commit-hard 'git reset --hard HEAD~1'
abbr -a gundo-commit 'git reset --soft HEAD~1'
abbr -a gundo-commit-hard 'git reset --hard HEAD~1'
abbr -a guncommit 'git reset --soft HEAD~1'
abbr -a gunadd 'git reset HEAD'
abbr -a gdiscard 'git checkout --'
abbr -a gcleaner 'git clean -dff'
abbr -a gcleanest 'git clean -dffx'
abbr -a gassume 'git update-index --assume-unchanged'
abbr -a gunassume 'git update-index --no-assume-unchanged'
abbr -a gbranches 'git branch -a'
abbr -a gtags 'git tag -n1 --list'
abbr -a gstashes 'git stash list'
abbr -a gtop 'git rev-parse --show-toplevel'
abbr -a gdefault-branch 'git config init.defaultBranch'
abbr -a gcurrent-branch 'git rev-parse --abbrev-ref HEAD'
abbr -a grepacker 'git repack -a -d -f --depth=300 --window=300 --window-memory=1g'
abbr -a gserve 'git "-c daemon.receivepack=true daemon --base-path=. --export-all --reuseaddr --verbose"'
abbr -a gtopic-begin 'git topic-start'
abbr -a gtopic-end 'git topic-finish'
abbr -a gcvs-i 'git cvsimport -k -a'
abbr -a gcvs-e 'git cvsexportcommit -u -p'
abbr -a gsvn-b 'git svn branch'
abbr -a gsvn-m 'git merge --squash'
abbr -a gsvn-c 'git svn dcommit'
