# Being selection on 'v' key
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clip"


# Select section on 'enter' key
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -sel clip"

# Bind ']' key for tmux paste
bind ] run "xclip -o | tmux load-buffer - && tmux paste-buffer"
