notify = [
  "bash",
  "-lc",
  "JSON=\"$1\"; LAST_MESSAGE=$(echo \"$JSON\" | jq -r '.\"last-assistant-message\" // \"Codex task completed\"'); osascript -e \"display notification \\\"$LAST_MESSAGE\\\" with title \\\"Codex\\\"\"",
  "notify",
]

[tools]
web_search = true

[model_providers.lmstudio]
name = "LMStudio"
base_url = "http://127.0.0.1:1234/v1"

[model_providers.ollama]
name = "Ollama"
base_url = "http://127.0.0.1:11434/v1"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"

[profiles.gpt-oss-20b]
model = "gpt-oss:20b"
model_provider = "ollama"

[profiles.gpt-oss-120b]
model = "openai/gpt-oss-120b"
model_provider = "lmstudio"

[profiles.qwen3-coder-30b]
model = "qwen/qwen3-coder-30b"
model_provider = "lmstudio"
