// Auto-generated by moshi-hook. Update with care.
import type { HookAPI } from "@oh-my-pi/pi-coding-agent/extensibility/hooks"
import { spawn } from "node:child_process"

const helperBinary = process.env.HOME + "/.local/bin/moshi-hook"

function firstString(...values: unknown[]): string {
  for (const value of values) {
    if (typeof value === "string" && value.length > 0) return value
  }
  return ""
}

function textFromContent(value: unknown): string {
  if (typeof value === "string") return value
  if (!Array.isArray(value)) return ""
  return value
    .map((chunk) => {
      if (typeof chunk === "string") return chunk
      if (chunk && typeof chunk === "object" && "text" in chunk) {
        const text = (chunk as { text?: unknown }).text
        return typeof text === "string" ? text : ""
      }
      return ""
    })
    .filter(Boolean)
    .join(" ")
}

function textFromMessage(value: unknown): string {
  if (!value || typeof value !== "object") return ""
  const message = value as Record<string, unknown>
  return firstString(
    textFromContent(message.content),
    textFromContent((message.message as Record<string, unknown> | undefined)?.content),
    textFromContent((message.entry as Record<string, unknown> | undefined)?.content),
  )
}

function modelLabel(model: unknown): string {
  if (!model || typeof model !== "object") return ""
  const obj = model as Record<string, unknown>
  return firstString(
    obj.displayName as string,
    obj.display_name as string,
    obj.name as string,
    obj.id as string,
    obj.modelId as string,
  )
}

function sessionID(event: Record<string, unknown>, ctx: Record<string, unknown>): string {
  const sessionManager = ctx.sessionManager as Record<string, unknown> | undefined
  const getSessionFile = sessionManager?.getSessionFile
  let sessionFile = ""
  if (typeof getSessionFile === "function") {
    try {
      sessionFile = String(getSessionFile.call(sessionManager) ?? "")
    } catch {}
  }
  return firstString(
    event.session_id as string,
    event.sessionId as string,
    sessionFile,
    ctx.cwd as string,
    "omp",
  )
}

function send(eventName: string, event: unknown, ctx: unknown, extra: Record<string, unknown> = {}) {
  const eventObj = event && typeof event === "object" ? event as Record<string, unknown> : {}
  const ctxObj = ctx && typeof ctx === "object" ? ctx as Record<string, unknown> : {}
  const payload = {
    hook_event_name: eventName,
    session_id: sessionID(eventObj, ctxObj),
    cwd: firstString(ctxObj.cwd as string, process.cwd()),
    model: modelLabel(ctxObj.model),
    event,
    ...extra,
  }

  try {
    const child = spawn(helperBinary, ["omp-hook"], {
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
    })
    child.stdin.end(JSON.stringify(payload))
    child.unref()
  } catch {
    // Hooks should never interrupt the user's OMP turn when Moshi is absent.
  }
}

export default function moshiOMPHook(omp: HookAPI): void {
  omp.on("session_start", (event, ctx) => {
    send("SessionStart", event, ctx)
  })

  omp.on("before_agent_start", (event, ctx) => {
    send("UserPromptSubmit", event, ctx, { prompt: event.prompt })
  })

  omp.on("agent_start", (event, ctx) => {
    send("AgentStart", event, ctx)
  })

  omp.on("agent_end", (event, ctx) => {
    const messages = Array.isArray(event.messages) ? event.messages : []
    const lastMessage = messages.length > 0 ? messages[messages.length - 1] : undefined
    send("AgentEnd", event, ctx, { last_assistant_message: textFromMessage(lastMessage) })
  })
}
