// Auto-generated by moshi-hook. Update with care.
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";
import { spawn } from "node:child_process";

const helperBinary = "@moshiHook@";

function firstString(...values: unknown[]): string {
  for (const value of values) {
    if (typeof value === "string" && value.length > 0) return value;
  }
  return "";
}

function textFromContent(value: unknown): string {
  if (typeof value === "string") return value;
  if (!Array.isArray(value)) return "";
  return value
    .map((chunk) => {
      if (typeof chunk === "string") return chunk;
      if (chunk && typeof chunk === "object" && "text" in chunk) {
        const text = (chunk as { text?: unknown }).text;
        return typeof text === "string" ? text : "";
      }
      return "";
    })
    .filter(Boolean)
    .join(" ");
}

function textFromMessage(value: unknown): string {
  if (!value || typeof value !== "object") return "";
  const message = value as Record<string, unknown>;
  return firstString(
    textFromContent(message.content),
    textFromContent(
      (message.message as Record<string, unknown> | undefined)?.content
    ),
    textFromContent(
      (message.entry as Record<string, unknown> | undefined)?.content
    )
  );
}

function modelLabel(model: unknown): string {
  if (!model || typeof model !== "object") return "";
  const obj = model as Record<string, unknown>;
  return firstString(
    obj.displayName as string,
    obj.display_name as string,
    obj.name as string,
    obj.id as string,
    obj.modelId as string
  );
}

function sessionID(
  event: Record<string, unknown>,
  ctx: Record<string, unknown>
): string {
  const sessionManager = ctx.sessionManager as
    | Record<string, unknown>
    | undefined;
  const getSessionId = sessionManager?.getSessionId;
  let managerID = "";
  if (typeof getSessionId === "function") {
    try {
      managerID = String(getSessionId.call(sessionManager) ?? "");
    } catch {}
  }
  return firstString(
    managerID,
    event.session_id as string,
    event.sessionId as string,
    "omp"
  );
}

function transcriptPath(ctx: Record<string, unknown>): string {
  const sessionManager = ctx.sessionManager as
    | Record<string, unknown>
    | undefined;
  const getSessionFile = sessionManager?.getSessionFile;
  if (typeof getSessionFile !== "function") return "";
  try {
    return String(getSessionFile.call(sessionManager) ?? "");
  } catch {
    return "";
  }
}

function send(
  eventName: string,
  event: unknown,
  ctx: unknown,
  extra: Record<string, unknown> = {}
) {
  const eventObj =
    event && typeof event === "object"
      ? (event as Record<string, unknown>)
      : {};
  const ctxObj =
    ctx && typeof ctx === "object" ? (ctx as Record<string, unknown>) : {};
  const payload = {
    hook_event_name: eventName,
    session_id: sessionID(eventObj, ctxObj),
    transcript_path: transcriptPath(ctxObj),
    cwd: firstString(ctxObj.cwd as string, process.cwd()),
    model: modelLabel(ctxObj.model),
    context_remaining: contextRemaining(ctxObj),
    event,
    ...extra,
  };

  try {
    const child = spawn(helperBinary, ["omp-hook"], {
      stdio: ["pipe", "ignore", "ignore"],
      detached: true,
    });
    child.stdin.end(JSON.stringify(payload));
    child.unref();
  } catch {
    // Hooks should never interrupt the user's OMP turn when Moshi is absent.
  }
}

function contextRemaining(ctx: Record<string, unknown>): number | undefined {
  const getContextUsage = ctx.getContextUsage;
  if (typeof getContextUsage !== "function") return undefined;
  try {
    const usage = getContextUsage.call(ctx) as
      | { percent?: unknown }
      | undefined;
    if (typeof usage?.percent !== "number" || !Number.isFinite(usage.percent))
      return undefined;
    return Math.max(1, Math.min(100, Math.round(100 - usage.percent)));
  } catch {
    return undefined;
  }
}

export default function moshiOMPHook(omp: ExtensionAPI): void {
  omp.on("session_start", (event, ctx) => {
    send("SessionStart", event, ctx);
  });

  omp.on("before_agent_start", (event, ctx) => {
    send("UserPromptSubmit", event, ctx, { prompt: event.prompt });
  });

  omp.on("agent_start", (event, ctx) => {
    send("AgentStart", event, ctx);
  });

  omp.on("session_stop", (event, ctx) => {
    send("AgentEnd", event, ctx, {
      last_assistant_message: textFromMessage(event.last_assistant_message),
    });
  });

  omp.on("tool_approval_requested", (event, ctx) => {
    send("PermissionRequest", event, ctx, {
      tool_name: event.toolName,
      tool_use_id: event.toolCallId,
      reason: event.reason,
    });
  });

  omp.on("tool_approval_resolved", (event, ctx) => {
    send("PermissionResolved", event, ctx, {
      tool_name: event.toolName,
      tool_use_id: event.toolCallId,
      approved: event.approved,
    });
  });

  omp.on("session_shutdown", (event, ctx) => {
    send("SessionEnd", event, ctx);
  });
}
