// Auto-generated by moshi-hook. Update with care.
import { createConnection } from "node:net";
import { homedir } from "node:os";
import { join as pathJoin } from "node:path";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { Database } from "bun:sqlite";
import type { Plugin } from "@opencode-ai/plugin";

// Kept for debug / manual invocation. Routine events go straight to the
// daemon's Unix socket (see resolveSocketPath) — no subprocess spawn.
const helperBinary = process.env.HOME + "/.local/bin/moshi-hook";

// Mirrors internal/config.SocketPath. The MOSHI_SOCKET_PATH override wins
// over the per-platform default so tests and dev daemons can point us at a
// throwaway socket.
function resolveSocketPath(): string {
  const override = process.env.MOSHI_SOCKET_PATH;
  if (override) return override;
  if (process.platform === "darwin") {
    return pathJoin(
      homedir(),
      "Library",
      "Application Support",
      "Moshi",
      "moshi-hook.sock"
    );
  }
  if (process.env.XDG_RUNTIME_DIR) {
    return pathJoin(process.env.XDG_RUNTIME_DIR, "moshi-hook.sock");
  }
  return "/tmp/moshi-hook.sock";
}

interface DaemonResponse {
  type?: string;
  decision?: string;
  error?: string;
}

// One-message-per-connection wire protocol (see internal/socket/server.go):
// dial, write one envelope as a JSON line, optionally read one response,
// close. Errors and timeouts resolve to null so callers degrade gracefully:
// fire-and-forget drops silently, permission.ask falls through to OpenCode's
// default handling.
function sendEnvelope(
  envelope: Record<string, unknown>,
  opts: { wait: boolean; waitTimeoutMs?: number }
): Promise<DaemonResponse | null> {
  return new Promise((resolve) => {
    let settled = false;
    const finish = (val: DaemonResponse | null) => {
      if (settled) return;
      settled = true;
      try {
        sock.destroy();
      } catch {}
      resolve(val);
    };

    const sock = createConnection({ path: resolveSocketPath() });
    sock.setNoDelay(true);
    sock.once("error", () => finish(null));

    if (opts.wait && opts.waitTimeoutMs) {
      setTimeout(() => finish(null), opts.waitTimeoutMs).unref?.();
    }

    sock.once("connect", () => {
      sock.write(JSON.stringify(envelope) + "\n");
      if (!opts.wait) {
        // Fire-and-forget from the caller's perspective, but still half-close
        // and read the daemon ack so the daemon does not log broken pipes.
        sock.end();
      }
    });

    const chunks: Buffer[] = [];
    sock.on("data", (b: Buffer) => chunks.push(b));
    const parse = () => {
      if (settled) return;
      const text = Buffer.concat(chunks).toString("utf8").trim();
      if (!text) return finish(null);
      try {
        finish(JSON.parse(text.split("\n")[0]) as DaemonResponse);
      } catch {
        finish(null);
      }
    };
    sock.once("end", parse);
    sock.once("close", parse);
  });
}

function projectNameFromCwd(cwd: string | undefined): string {
  if (!cwd) return "";
  const trimmed = cwd.replace(/\/+$/, "");
  const idx = trimmed.lastIndexOf("/");
  return idx >= 0 ? trimmed.slice(idx + 1) : trimmed;
}

interface TerminalContext {
  terminalKind: string;
  tmuxSession: string;
  tmuxWindow: string;
  tmuxPane: string;
  tmuxSocket: string;
  zellijSession: string;
  zellijPane: string;
  herdrSession: string;
  herdrPane: string;
  herdrWorkspaceId: string;
  herdrWorkspace: string;
  herdrTabId: string;
  herdrTab: string;
}

function tmuxSocketFromEnv(value: string | undefined): string {
  if (!value) return "";
  const idx = value.indexOf(",");
  return idx > 0 ? value.slice(0, idx) : "";
}

function herdrFocusedPane(session: string): string {
  if (process.env.HERDR_ENV !== "1") return "";
  const args: string[] = [];
  if (session) args.push("--session", session);
  args.push("pane", "list");
  try {
    const result = spawnSync("herdr", args, { encoding: "utf8", timeout: 300 });
    const text = typeof result.stdout === "string" ? result.stdout : "";
    if (!text) return "";
    const payload = JSON.parse(text) as {
      result?: { panes?: Array<{ pane_id?: string; focused?: boolean }> };
    };
    const pane = payload.result?.panes?.find((p) => p.focused && p.pane_id);
    return pane?.pane_id ?? "";
  } catch {
    return "";
  }
}

function herdrPaneWorkspace(
  session: string,
  paneId: string
): {
  paneId: string;
  workspaceId: string;
  workspace: string;
  tabId: string;
  tab: string;
} {
  if (process.env.HERDR_ENV !== "1" || !paneId)
    return { paneId, workspaceId: "", workspace: "", tabId: "", tab: "" };
  const paneArgs: string[] = [];
  if (session) paneArgs.push("--session", session);
  paneArgs.push("pane", "get", paneId);
  try {
    const paneResult = spawnSync("herdr", paneArgs, {
      encoding: "utf8",
      timeout: 300,
    });
    const paneText =
      typeof paneResult.stdout === "string" ? paneResult.stdout : "";
    const panePayload = paneText
      ? (JSON.parse(paneText) as {
          result?: {
            pane?: { pane_id?: string; workspace_id?: string; tab_id?: string };
          };
        })
      : {};
    const canonicalPaneId = panePayload.result?.pane?.pane_id ?? paneId;
    let workspaceId = panePayload.result?.pane?.workspace_id ?? "";
    let tabId = panePayload.result?.pane?.tab_id ?? "";
    if (!workspaceId || !tabId) {
      const paneListArgs: string[] = [];
      if (session) paneListArgs.push("--session", session);
      paneListArgs.push("pane", "list");
      const paneListResult = spawnSync("herdr", paneListArgs, {
        encoding: "utf8",
        timeout: 300,
      });
      const paneListText =
        typeof paneListResult.stdout === "string" ? paneListResult.stdout : "";
      const paneListPayload = paneListText
        ? (JSON.parse(paneListText) as {
            result?: {
              panes?: Array<{
                pane_id?: string;
                workspace_id?: string;
                tab_id?: string;
                focused?: boolean;
              }>;
            };
          })
        : {};
      const panes = paneListPayload.result?.panes ?? [];
      const pane =
        panes.find((p) => p.pane_id === canonicalPaneId) ??
        panes.find((p) => p.focused);
      workspaceId = workspaceId || pane?.workspace_id || "";
      tabId = tabId || pane?.tab_id || "";
    }
    if (!workspaceId)
      return {
        paneId: canonicalPaneId,
        workspaceId: "",
        workspace: "",
        tabId,
        tab: "",
      };
    const workspaceArgs: string[] = [];
    if (session) workspaceArgs.push("--session", session);
    workspaceArgs.push("workspace", "list");
    const workspaceResult = spawnSync("herdr", workspaceArgs, {
      encoding: "utf8",
      timeout: 300,
    });
    const workspaceText =
      typeof workspaceResult.stdout === "string" ? workspaceResult.stdout : "";
    const workspacePayload = workspaceText
      ? (JSON.parse(workspaceText) as {
          result?: {
            workspaces?: Array<{ workspace_id?: string; label?: string }>;
          };
        })
      : {};
    const workspace =
      workspacePayload.result?.workspaces?.find(
        (w) => w.workspace_id === workspaceId
      )?.label ?? "";
    const tabArgs: string[] = [];
    if (session) tabArgs.push("--session", session);
    tabArgs.push("tab", "list", "--workspace", workspaceId);
    const tabResult = spawnSync("herdr", tabArgs, {
      encoding: "utf8",
      timeout: 300,
    });
    const tabText =
      typeof tabResult.stdout === "string" ? tabResult.stdout : "";
    const tabPayload = tabText
      ? (JSON.parse(tabText) as {
          result?: { tabs?: Array<{ tab_id?: string; label?: string }> };
        })
      : {};
    const tab =
      tabPayload.result?.tabs?.find((t) => t.tab_id === tabId)?.label ?? "";
    return { paneId: canonicalPaneId, workspaceId, workspace, tabId, tab };
  } catch {
    return { paneId, workspaceId: "", workspace: "", tabId: "", tab: "" };
  }
}

function resolveTerminalContext(): TerminalContext {
  const tmuxPane = process.env.TMUX_PANE ?? "";
  const tmuxSocket = tmuxSocketFromEnv(process.env.TMUX);
  let tmuxSession = "";
  let tmuxWindow = "";
  if (process.env.TMUX) {
    const args = ["display-message", "-p"];
    if (tmuxPane) args.push("-t", tmuxPane);
    args.push("#S\t#I");
    try {
      const result = spawnSync("tmux", args, {
        encoding: "utf8",
        timeout: 200,
      });
      const text =
        typeof result.stdout === "string" ? result.stdout.trim() : "";
      if (text) {
        const parts = text.split("\t", 2);
        tmuxSession = parts[0] ?? "";
        tmuxWindow = parts[1] ?? "";
      }
    } catch {}
  }
  const zellijSession = process.env.ZELLIJ_SESSION_NAME ?? "";
  const zellijPane = process.env.ZELLIJ_PANE_ID ?? "";
  const herdrSession =
    process.env.HERDR_ENV === "1" ? (process.env.HERDR_SESSION ?? "") : "";
  const herdrInfo = herdrPaneWorkspace(
    herdrSession,
    process.env.HERDR_ENV === "1"
      ? (process.env.HERDR_PANE_ID ?? herdrFocusedPane(herdrSession))
      : ""
  );
  const herdrPane = herdrInfo.paneId;
  const herdrWorkspaceId = herdrInfo.workspaceId;
  const herdrWorkspace = herdrInfo.workspace;
  const herdrTabId = herdrInfo.tabId;
  const herdrTab = herdrInfo.tab;
  let terminalKind = "";
  if (tmuxSession) terminalKind = "tmux";
  else if (process.env.HERDR_ENV === "1") terminalKind = "herdr";
  else if (process.env.ZELLIJ || zellijSession || zellijPane)
    terminalKind = "zellij";
  return {
    terminalKind,
    tmuxSession,
    tmuxWindow,
    tmuxPane,
    tmuxSocket,
    zellijSession,
    zellijPane,
    herdrSession,
    herdrPane,
    herdrWorkspaceId,
    herdrWorkspace,
    herdrTabId,
    herdrTab,
  };
}

const terminalContext = resolveTerminalContext();

function projectNameForCwd(cwd: string | undefined): string {
  return (
    terminalContext.tmuxSession ||
    terminalContext.herdrSession ||
    terminalContext.zellijSession ||
    projectNameFromCwd(cwd)
  );
}

const modelContextLimits = new Map<string, number>();
let modelLimitsReady: Promise<void> = Promise.resolve();

async function refreshOpenCodeModelLimits(
  client: Record<string, unknown>,
  directory: string
): Promise<void> {
  const providers = client.providers;
  if (typeof providers !== "function") return;
  try {
    const result = await providers.call(client, { query: { directory } });
    const data =
      result && typeof result === "object" && "data" in result
        ? (result as Record<string, unknown>).data
        : result;
    const list =
      data &&
      typeof data === "object" &&
      Array.isArray((data as Record<string, unknown>).providers)
        ? ((data as Record<string, unknown>).providers as Array<
            Record<string, unknown>
          >)
        : [];
    for (const provider of list) {
      const providerID = stringProp(provider, "id");
      const models = provider.models;
      if (!providerID || !models || typeof models !== "object") continue;
      for (const [modelID, raw] of Object.entries(
        models as Record<string, unknown>
      )) {
        if (!raw || typeof raw !== "object") continue;
        const limit = (raw as Record<string, unknown>).limit;
        const context =
          limit && typeof limit === "object"
            ? (limit as Record<string, unknown>).context
            : undefined;
        if (typeof context !== "number" || context <= 0) continue;
        modelContextLimits.set(providerID + "\0" + modelID, context);
        modelContextLimits.set(modelID, context);
      }
    }
  } catch {}
}

function resolveOpenCodeDataDir(): string {
  if (process.env.XDG_DATA_HOME)
    return pathJoin(process.env.XDG_DATA_HOME, "opencode");
  return pathJoin(homedir(), ".local", "share", "opencode");
}

function readJSONFile(path: string): Record<string, unknown> | null {
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8"));
    return parsed && typeof parsed === "object"
      ? (parsed as Record<string, unknown>)
      : null;
  } catch {
    return null;
  }
}

function tokenTotal(tokens: unknown): number {
  if (!tokens || typeof tokens !== "object") return 0;
  const rec = tokens as Record<string, unknown>;
  const direct = ["input", "output", "reasoning"].reduce(
    (sum, key) =>
      sum + (typeof rec[key] === "number" ? (rec[key] as number) : 0),
    0
  );
  if (direct > 0) return direct;
  return typeof rec.total === "number" && rec.total > 0 ? rec.total : 0;
}

function contextRemainingFromUsage(used: number, window: number): number {
  if (used <= 0 || window <= 0) return 0;
  const usedPct = Math.min(100, Math.floor((used * 100) / window));
  const remaining = 100 - usedPct;
  return remaining === 0 ? 1 : remaining;
}

function openCodeContextRemainingForSession(
  sessionID: string | undefined
): number {
  if (!sessionID) return 0;
  const fromDB = openCodeContextRemainingFromDB(sessionID);
  if (fromDB > 0) return fromDB;
  return openCodeContextRemainingFromMessageFiles(sessionID);
}

function openCodeContextRemainingFromDB(sessionID: string): number {
  let db: Database | undefined;
  try {
    db = new Database(pathJoin(resolveOpenCodeDataDir(), "opencode.db"), {
      readonly: true,
    });
    const row = db
      .query(
        "select model, tokens_input, tokens_output, tokens_reasoning from session where id = ? limit 1"
      )
      .get(sessionID) as Record<string, unknown> | null;
    if (!row) return 0;
    const used =
      numberProp(row, "tokens_input") +
      numberProp(row, "tokens_output") +
      numberProp(row, "tokens_reasoning");
    if (used <= 0) return 0;
    const model = parseModelRef(row.model);
    const window =
      modelContextLimits.get(model.providerID + "\0" + model.modelID) ??
      modelContextLimits.get(model.modelID) ??
      0;
    return contextRemainingFromUsage(used, window);
  } catch {
    return 0;
  } finally {
    try {
      db?.close();
    } catch {}
  }
}

function openCodeContextRemainingFromMessageFiles(sessionID: string): number {
  let files: string[];
  const dir = pathJoin(
    resolveOpenCodeDataDir(),
    "storage",
    "message",
    sessionID
  );
  try {
    files = readdirSync(dir).filter((name) => name.endsWith(".json"));
  } catch {
    return 0;
  }
  files.sort((a, b) => {
    try {
      return (
        statSync(pathJoin(dir, b)).mtimeMs - statSync(pathJoin(dir, a)).mtimeMs
      );
    } catch {
      return b.localeCompare(a);
    }
  });
  for (const file of files) {
    const msg = readJSONFile(pathJoin(dir, file));
    if (!msg) continue;
    const used = tokenTotal(msg.tokens);
    if (used <= 0) continue;
    const providerID = stringProp(msg, "providerID");
    const modelID = stringProp(msg, "modelID");
    const window =
      modelContextLimits.get(providerID + "\0" + modelID) ??
      modelContextLimits.get(modelID) ??
      0;
    const remaining = contextRemainingFromUsage(used, window);
    if (remaining > 0) return remaining;
  }
  return 0;
}

function numberProp(obj: Record<string, unknown>, key: string): number {
  const val = obj[key];
  return typeof val === "number" && val > 0 ? val : 0;
}

function parseModelRef(raw: unknown): { providerID: string; modelID: string } {
  if (typeof raw === "string" && raw.length > 0) {
    try {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === "object") {
        const rec = parsed as Record<string, unknown>;
        return {
          providerID: stringProp(rec, "providerID"),
          modelID: stringProp(rec, "id", "modelID"),
        };
      }
    } catch {}
  }
  return { providerID: "", modelID: "" };
}

function withContextRemaining(
  envelope: Record<string, unknown>,
  sessionID: string | undefined
): Record<string, unknown> {
  const contextRemaining = openCodeContextRemainingForSession(sessionID);
  if (contextRemaining > 0) envelope.contextRemaining = contextRemaining;
  return envelope;
}

function prettyToolName(toolName: string) {
  switch (toolName) {
    case "bash":
      return "Bash";
    case "edit":
      return "Edit";
    case "write":
      return "Write";
    case "webfetch":
      return "WebFetch";
    case "websearch":
    case "codesearch":
      return "WebSearch";
    case "task":
      return "Task";
    default:
      return toolName;
  }
}

// Mirrors internal/cli/hook.go newSessionID — 16 hex chars, used when
// OpenCode hands us an event with no sessionID (rare but possible on
// initialisation paths).
function newSessionID(): string {
  const buf = new Uint8Array(8);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

function subtitleForPermission(name: string): string {
  switch (name) {
    case "bash":
      return "Waiting for command approval";
    case "edit":
      return "Waiting for file edit approval";
    case "external_directory":
      return "Waiting for directory access approval";
    default:
      return "Waiting for approval";
  }
}

function stringProp(obj: Record<string, unknown>, ...keys: string[]): string {
  for (const key of keys) {
    const val = obj[key];
    if (typeof val === "string" && val.length > 0) return val;
  }
  return "";
}

function patternsFromPermission(permission: Record<string, unknown>): string[] {
  const rawPatterns = permission.patterns ?? permission.pattern;
  const patterns: string[] = Array.isArray(rawPatterns)
    ? rawPatterns.filter(
        (p): p is string => typeof p === "string" && p.length > 0
      )
    : typeof rawPatterns === "string" && rawPatterns.length > 0
      ? [rawPatterns]
      : [];
  return patterns;
}

function permissionName(permission: Record<string, unknown>): string {
  return stringProp(permission, "permission", "type") || "permission";
}

function summarizePermission(permission: Record<string, unknown>): string {
  const patterns = patternsFromPermission(permission);
  const title = stringProp(permission, "title");
  if (title) return title;
  const name = permissionName(permission);
  if (patterns.length === 0) {
    return name ? name + " permission requested" : "Permission requested";
  }
  return name + ": " + patterns[0];
}

function sendSessionUpdate(
  eventName: string,
  sessionID: string | undefined,
  directory: string,
  toolName?: string,
  category?: string,
  title?: string,
  message?: string
): void {
  void modelLimitsReady.finally(() => {
    void sendEnvelope(
      withContextRemaining(
        {
          type: "session.update",
          source: "opencode",
          sessionId: sessionID || newSessionID(),
          eventName,
          cwd: directory,
          projectName: projectNameForCwd(directory),
          terminalKind: terminalContext.terminalKind,
          tmuxSession: terminalContext.tmuxSession,
          tmuxWindow: terminalContext.tmuxWindow,
          tmuxPane: terminalContext.tmuxPane,
          tmuxSocket: terminalContext.tmuxSocket,
          zellijSession: terminalContext.zellijSession,
          zellijPane: terminalContext.zellijPane,
          herdrSession: terminalContext.herdrSession,
          herdrPane: terminalContext.herdrPane,
          herdrWorkspaceId: terminalContext.herdrWorkspaceId,
          herdrWorkspace: terminalContext.herdrWorkspace,
          herdrTabId: terminalContext.herdrTabId,
          herdrTab: terminalContext.herdrTab,
          toolName: toolName ?? "",
          category: category ?? "",
          title: title ?? "",
          message: message ?? "",
          requestedAt: new Date().toISOString(),
        },
        sessionID
      ),
      { wait: false }
    );
  });
}

function sendSessionClosed(
  eventName: string,
  sessionID: string | undefined,
  directory: string
): void {
  void modelLimitsReady.finally(() => {
    void sendEnvelope(
      {
        type: "session.closed",
        source: "opencode",
        sessionId: sessionID || newSessionID(),
        eventName,
        category: "session_ended",
        cwd: directory,
        projectName: projectNameForCwd(directory),
        terminalKind: terminalContext.terminalKind,
        tmuxSession: terminalContext.tmuxSession,
        tmuxWindow: terminalContext.tmuxWindow,
        tmuxPane: terminalContext.tmuxPane,
        tmuxSocket: terminalContext.tmuxSocket,
        zellijSession: terminalContext.zellijSession,
        zellijPane: terminalContext.zellijPane,
        herdrSession: terminalContext.herdrSession,
        herdrPane: terminalContext.herdrPane,
        herdrWorkspaceId: terminalContext.herdrWorkspaceId,
        herdrWorkspace: terminalContext.herdrWorkspace,
        herdrTabId: terminalContext.herdrTabId,
        herdrTab: terminalContext.herdrTab,
        title: "OpenCode session ended",
        requestedAt: new Date().toISOString(),
      },
      { wait: false }
    );
  });
}

const activeSessions = new Set<string>();
const idlePublishedSessions = new Set<string>();
const lastUserPrompts = new Map<string, string>();
const lastAssistantTitles = new Map<string, string>();
const messageRoles = new Map<string, string>();
const assistantTextByMessage = new Map<string, string>();

function sessionKey(sessionID: string | undefined, cwd: string): string {
  return sessionID && sessionID.length > 0 ? sessionID : "cwd:" + cwd;
}

function relatedSessionKeys(
  sessionID: string | undefined,
  cwd: string
): string[] {
  const keys = [sessionKey(sessionID, cwd), "cwd:" + cwd];
  if (activeSessions.size === 1) {
    for (const key of activeSessions) keys.push(key);
  }
  return Array.from(new Set(keys.filter((key) => key.length > 4)));
}

function firstValue(map: Map<string, string>, keys: string[]): string {
  for (const key of keys) {
    const val = map.get(key);
    if (val) return val;
  }
  return "";
}

function markSessionActive(sessionID: string | undefined, cwd: string): void {
  const key =
    relatedSessionKeys(sessionID, cwd)[0] || sessionKey(sessionID, cwd);
  activeSessions.add(key);
  for (const related of relatedSessionKeys(sessionID, cwd)) {
    idlePublishedSessions.delete(related);
  }
}

function sendIdleIfActive(
  eventName: string,
  sessionID: string | undefined,
  cwd: string
): void {
  const keys = relatedSessionKeys(sessionID, cwd);
  const key = keys.find((candidate) => activeSessions.has(candidate)) || "";
  if (!key || keys.some((candidate) => idlePublishedSessions.has(candidate)))
    return;
  const prompt = firstValue(lastUserPrompts, keys);
  if (!prompt) return;
  idlePublishedSessions.add(key);
  sendSessionUpdate(
    eventName,
    sessionID,
    cwd,
    undefined,
    "task_complete",
    firstValue(lastAssistantTitles, keys) || "OpenCode idle",
    prompt
  );
}

function textFromParts(parts: unknown): string {
  if (!Array.isArray(parts)) return "";
  const text = parts
    .map((part) => {
      if (!part || typeof part !== "object") return "";
      const rec = part as Record<string, unknown>;
      return rec.type === "text" && typeof rec.text === "string"
        ? rec.text
        : "";
    })
    .filter((s) => s.length > 0)
    .join("\n")
    .trim();
  return text.length > 200 ? text.slice(0, 197) + "..." : text;
}

function formatUserPrompt(prompt: string): string {
  const text = prompt.trim();
  if (!text) return "";
  const clipped = text.length > 200 ? text.slice(0, 197) + "..." : text;
  return clipped;
}

function rememberUserPrompt(
  sessionID: string | undefined,
  cwd: string,
  prompt: string
): string {
  const formatted = formatUserPrompt(prompt);
  if (!formatted) return "";
  for (const key of relatedSessionKeys(sessionID, cwd)) {
    lastUserPrompts.set(key, formatted);
  }
  return formatted;
}

function titleForPromptStart(
  sessionID: string | undefined,
  cwd: string
): string {
  return firstValue(lastAssistantTitles, relatedSessionKeys(sessionID, cwd));
}

function rememberMessageRole(info: unknown): void {
  if (!info || typeof info !== "object") return;
  const rec = info as Record<string, unknown>;
  const id = typeof rec.id === "string" ? rec.id : "";
  const role = typeof rec.role === "string" ? rec.role : "";
  if (id && role) messageRoles.set(id, role);
}

function rememberAssistantText(
  sessionID: string | undefined,
  cwd: string,
  messageID: string,
  text: string,
  append: boolean
): void {
  if (!messageID || !text) return;
  if (messageRoles.get(messageID) !== "assistant") return;
  const next = append
    ? (assistantTextByMessage.get(messageID) || "") + text
    : text;
  assistantTextByMessage.set(messageID, next);
  const title = next.trim();
  if (title) {
    const clipped = title.length > 80 ? title.slice(0, 77) + "..." : title;
    for (const key of relatedSessionKeys(sessionID, cwd)) {
      lastAssistantTitles.set(key, clipped);
    }
  }
}

function eventRecord(event: { properties?: unknown }): Record<string, unknown> {
  return event.properties && typeof event.properties === "object"
    ? (event.properties as Record<string, unknown>)
    : {};
}

function sessionIDFromProperties(
  props: Record<string, unknown>
): string | undefined {
  const direct = stringProp(props, "sessionID", "sessionId", "id");
  if (direct) return direct;
  const info = props.info;
  if (info && typeof info === "object")
    return stringProp(
      info as Record<string, unknown>,
      "id",
      "sessionID",
      "sessionId"
    );
  return undefined;
}

function directoryFromProperties(
  props: Record<string, unknown>,
  fallback: string
): string {
  const direct = stringProp(props, "directory", "cwd");
  if (direct) return direct;
  const info = props.info;
  if (info && typeof info === "object") {
    const fromInfo = stringProp(
      info as Record<string, unknown>,
      "directory",
      "cwd"
    );
    if (fromInfo) return fromInfo;
  }
  return fallback;
}

function permissionFromEventProperties(
  props: Record<string, unknown>
): Record<string, unknown> {
  const nested = props.permission;
  if (nested && typeof nested === "object")
    return nested as Record<string, unknown>;
  return props;
}

function summarizeQuestion(props: Record<string, unknown>): string {
  const direct = stringProp(
    props,
    "question",
    "prompt",
    "message",
    "text",
    "title"
  );
  if (direct) return direct;
  const nested = props.question;
  if (nested && typeof nested === "object") {
    const nestedText = stringProp(
      nested as Record<string, unknown>,
      "question",
      "prompt",
      "message",
      "text",
      "title"
    );
    if (nestedText) return nestedText;
  }
  return "";
}

function sendTerminalInputRequired(
  eventName: string,
  props: Record<string, unknown>,
  directory: string,
  title: string,
  fallbackMessage: string
): void {
  const cwd = directoryFromProperties(props, directory);
  const sessionID = sessionIDFromProperties(props);
  const actionID =
    stringProp(
      props,
      "id",
      "questionID",
      "questionId",
      "requestID",
      "requestId"
    ) || newSessionID();
  const message = summarizeQuestion(props) || fallbackMessage;
  void modelLimitsReady.finally(() => {
    void sendEnvelope(
      withContextRemaining(
        {
          type: "session.update",
          source: "opencode",
          sessionId: sessionID || newSessionID(),
          actionId: actionID,
          eventName,
          phase: "waitingForApproval",
          category: "approval_required",
          cwd,
          projectName: projectNameForCwd(cwd),
          terminalKind: terminalContext.terminalKind,
          tmuxSession: terminalContext.tmuxSession,
          tmuxWindow: terminalContext.tmuxWindow,
          tmuxPane: terminalContext.tmuxPane,
          tmuxSocket: terminalContext.tmuxSocket,
          zellijSession: terminalContext.zellijSession,
          zellijPane: terminalContext.zellijPane,
          herdrSession: terminalContext.herdrSession,
          herdrPane: terminalContext.herdrPane,
          herdrWorkspaceId: terminalContext.herdrWorkspaceId,
          herdrWorkspace: terminalContext.herdrWorkspace,
          herdrTabId: terminalContext.herdrTabId,
          herdrTab: terminalContext.herdrTab,
          title,
          subtitle: "Answer in terminal",
          message,
          requestedAt: new Date().toISOString(),
        },
        sessionID
      ),
      { wait: false }
    );
  });
}

function statusTypeFromProperties(props: Record<string, unknown>): string {
  const status = props.status;
  if (status && typeof status === "object")
    return stringProp(status as Record<string, unknown>, "type");
  return stringProp(props, "status");
}

function openCodeReplyForDecision(
  decision: string | undefined
): "once" | "reject" | null {
  switch (decision) {
    case "approve":
      return "once";
    case "deny":
      return "reject";
    default:
      return null;
  }
}

const approvalRequests = new Map<string, Promise<DaemonResponse | null>>();

function requestMoshiApproval(
  permission: Record<string, unknown>,
  directory: string,
  eventName: string
): Promise<DaemonResponse | null> | null {
  const actionID = stringProp(
    permission,
    "id",
    "permissionID",
    "permissionId",
    "requestID",
    "requestId"
  );
  if (!actionID) return null;

  const existing = approvalRequests.get(actionID);
  if (existing) return existing;

  const name = permissionName(permission);
  const expiresAt = new Date(Date.now() + 5 * 60_000).toISOString();
  const promise = modelLimitsReady
    .then(() =>
      sendEnvelope(
        withContextRemaining(
          {
            type: "approval.request",
            source: "opencode",
            sessionId:
              stringProp(permission, "sessionID", "sessionId") ||
              newSessionID(),
            actionId: actionID,
            eventName,
            phase: "waitingForApproval",
            category: "approval_required",
            cwd: directory,
            projectName: projectNameForCwd(directory),
            terminalKind: terminalContext.terminalKind,
            tmuxSession: terminalContext.tmuxSession,
            tmuxWindow: terminalContext.tmuxWindow,
            tmuxPane: terminalContext.tmuxPane,
            tmuxSocket: terminalContext.tmuxSocket,
            zellijSession: terminalContext.zellijSession,
            zellijPane: terminalContext.zellijPane,
            herdrSession: terminalContext.herdrSession,
            herdrPane: terminalContext.herdrPane,
            herdrWorkspaceId: terminalContext.herdrWorkspaceId,
            herdrWorkspace: terminalContext.herdrWorkspace,
            herdrTabId: terminalContext.herdrTabId,
            herdrTab: terminalContext.herdrTab,
            toolName: name,
            title: "OpenCode permission",
            subtitle: subtitleForPermission(name),
            message: summarizePermission(permission),
            expiresAt,
            requestedAt: new Date().toISOString(),
          },
          stringProp(permission, "sessionID", "sessionId")
        ),
        { wait: true, waitTimeoutMs: 5 * 60_000 + 5_000 }
      )
    )
    .finally(() => {
      approvalRequests.delete(actionID);
    });
  approvalRequests.set(actionID, promise);
  return promise;
}

async function replyToOpenCodePermission(
  client: Record<string, unknown>,
  permission: Record<string, unknown>,
  reply: "once" | "reject",
  directory: string
): Promise<void> {
  const actionID = stringProp(
    permission,
    "id",
    "permissionID",
    "permissionId",
    "requestID",
    "requestId"
  );
  const sessionID = stringProp(permission, "sessionID", "sessionId");
  const fn = client.postSessionIdPermissionsPermissionId;
  if (!actionID || !sessionID || typeof fn !== "function") return;
  try {
    await fn.call(client, {
      path: { id: sessionID, permissionID: actionID },
      query: { directory },
      body: { response: reply },
    });
  } catch {}
}

const server: Plugin = async ({ directory, client }) => {
  modelLimitsReady = refreshOpenCodeModelLimits(
    client as unknown as Record<string, unknown>,
    directory
  );
  return {
    "chat.message": async (input, output) => {
      const prompt = textFromParts(output.parts);
      const formatted = rememberUserPrompt(input.sessionID, directory, prompt);
      if (!formatted) return;
      markSessionActive(input.sessionID, directory);
      const title =
        titleForPromptStart(input.sessionID, directory) || "OpenCode started";
      sendSessionUpdate(
        "chat.message",
        input.sessionID,
        directory,
        undefined,
        "session_started",
        title,
        formatted
      );
    },
    event: async ({ event }) => {
      const props = eventRecord(event);
      switch (event.type) {
        case "session.created": {
          const cwd = directoryFromProperties(props, directory);
          sendSessionUpdate(
            "session.created",
            sessionIDFromProperties(props),
            cwd,
            undefined,
            "",
            "OpenCode started"
          );
          break;
        }
        case "message.updated": {
          rememberMessageRole(props.info);
          break;
        }
        case "message.part.delta": {
          const cwd = directoryFromProperties(props, directory);
          const messageID = stringProp(props, "messageID", "messageId");
          const field = stringProp(props, "field");
          const delta = stringProp(props, "delta");
          if (field === "text")
            rememberAssistantText(
              sessionIDFromProperties(props),
              cwd,
              messageID,
              delta,
              true
            );
          break;
        }
        case "message.part.updated": {
          const cwd = directoryFromProperties(props, directory);
          const part = props.part;
          if (part && typeof part === "object") {
            const rec = part as Record<string, unknown>;
            const messageID =
              typeof rec.messageID === "string" ? rec.messageID : "";
            if (rec.type === "text" && typeof rec.text === "string")
              rememberAssistantText(
                sessionIDFromProperties(props),
                cwd,
                messageID,
                rec.text,
                false
              );
          }
          break;
        }
        case "session.status": {
          const statusType = statusTypeFromProperties(props);
          const cwd = directoryFromProperties(props, directory);
          const sessionID = sessionIDFromProperties(props);
          if (statusType === "busy") {
            break;
          } else if (statusType === "idle") {
            sendIdleIfActive("session.status", sessionID, cwd);
          } else {
            sendSessionUpdate(
              "session.status",
              sessionID,
              cwd,
              undefined,
              "",
              "OpenCode started",
              statusType
            );
          }
          break;
        }
        case "session.idle": {
          const cwd = directoryFromProperties(props, directory);
          sendIdleIfActive("session.idle", sessionIDFromProperties(props), cwd);
          break;
        }
        case "session.deleted": {
          const cwd = directoryFromProperties(props, directory);
          sendSessionClosed(
            "session.deleted",
            sessionIDFromProperties(props),
            cwd
          );
          break;
        }
        case "permission.asked":
        case "permission.updated": {
          const permission = permissionFromEventProperties(props);
          const promise = requestMoshiApproval(
            permission,
            directory,
            event.type
          );
          if (!promise) break;
          const result = await promise;
          const reply = openCodeReplyForDecision(result?.decision);
          if (reply)
            await replyToOpenCodePermission(
              client as unknown as Record<string, unknown>,
              permission,
              reply,
              directory
            );
          break;
        }
        case "permission.replied":
          sendSessionUpdate(
            "permission.replied",
            sessionIDFromProperties(props),
            directory
          );
          break;
        case "question.asked":
          sendTerminalInputRequired(
            "question.asked",
            props,
            directory,
            "OpenCode needs input",
            "Input requested"
          );
          break;
        case "question.replied":
        case "question.rejected":
          sendSessionUpdate(
            event.type,
            sessionIDFromProperties(props),
            directory
          );
          break;
        case "session.error":
          sendTerminalInputRequired(
            "session.error",
            props,
            directory,
            "OpenCode blocked",
            "OpenCode reported an error"
          );
          break;
        default:
          break;
      }
    },
    "tool.execute.before": async (input) => {
      markSessionActive(input.sessionID, directory);
    },
    "tool.execute.after": async (input) => {
      markSessionActive(input.sessionID, directory);
    },
    "permission.ask": async (input, output) => {
      const result = await requestMoshiApproval(
        input as Record<string, unknown>,
        directory,
        "permission.ask"
      );

      switch (result?.decision) {
        case "approve":
          output.status = "allow";
          break;
        case "deny":
          output.status = "deny";
          break;
        default:
          break;
      }
    },
  };
};

export default {
  id: "moshi-hooks",
  server,
};
