wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: lightblue
      normal: gray
  grid:
    columns: [27, 30, 30, 30, 30, 30]
    rows: [10, 10, 10, 3]
  refreshInterval: 1
  mods:
    github:
      apiKey: "122ecbbfbe39fd7a11f11499747132145e02c76e"
      baseURL: ""
      customQueries:
        openIssues:
          title: "Issues"
          filter: "is:issue state:open"
      enabled: true
      enableStatus: true
      position:
        top: 0
        left: 0
        height: 3
        width: 1
      refreshInterval: 300
      repositories:
        - "shunkakinoki/shunkakinoki"
      uploadURL: ""
      username: "shunkakinoki"
      title: "Github"
    power:
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      title: "Battery"
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 300
    security:
      enabled: true
      position:
        top: 0
        left: 3
        height: 1
        width: 1
      refreshInterval: 3600
    prettyweather:
      enabled: true
      city: "Tokyo"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
    docker:
      type: docker
      enabled: true
      labelColor: lightblue
      position:
        top:  1
        left: 2
        height: 1
        width: 1
      refreshInterval: 1
      title: "Docker"
    kubernetes:
      enabled: true
      kubeconfig: "/Users/shunkakinoki/.kube/config"
      objects:
      - deployments
      - nodes
      - pods
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 300
      title: "Kubernetes"
    digitalclock:
      color: lightblue
      enabled: true
      font: bigfont
      hourFormat: 24
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 1
      title: "Time"
      type: "digitalclock"
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Berlin: "Europe/Berlin"
        Dubai: "Asia/Dubai"
        San Francisco: "America/Los Angeles"
        Sao Paolo: "America/Sao_Paulo"
        Shanghai: "Asia/Shanghai"
        New Delhi: "Asia/Kolkata"
        New York: "America/New York"
        UTC: "Etc/UTC"
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
      sort: "chronological"
    nbascore:
      enabled: true
      position:
        top: 2
        left: 3
        height: 1
        width: 1
      refreshInterval: 600
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 4
      refreshInterval: 30
      title: "Uptime"
      type: cmdrunner
