suppress_unstable_features_warning = true
web_search = "cached"
model = "__GPT_CODEX__"
model_reasoning_effort = "xhigh"
oss_provider = "lmstudio"

[features]
apply_patch_freeform = true
apps = true
artifact = true
child_agents_md = true
code_mode = true
codex_git_commit = true
codex_hooks = true
enable_fanout = true
enable_request_compression = true
fast_mode = true
guardian_approval = true
image_detail_original = true
image_generation = false
js_repl = true
memories = true
multi_agent = true
multi_agent_v2 = true
personality = true
plugins = true
prevent_idle_sleep = true
realtime_conversation = true
runtime_metrics = true
shell_snapshot = true
shell_tool = true
tool_call_mcp_elicitation = true
tool_search = true
tool_suggest = true
tui_app_server = true
unified_exec = true
voice_transcription = true

[model_providers.cliproxyapi]
name = "CLIProxyAPI"
base_url = "http://localhost:8317/v1"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"

[profiles.gemma]
model = "__GEMMA__"
model_provider = "lmstudio"
model_reasoning_effort = "minimal"

[profiles.qwen-local]
model = "__QWEN_LOCAL__"
model_provider = "lmstudio"
model_reasoning_effort = "minimal"
