name: Auto Approve
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  auto-approve-renovate:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve Renovate PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  auto-approve-check:
    if: always()
    needs:
      - auto-approve-renovate
    runs-on: ubuntu-latest
    steps:
      - name: Alls Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips:
            - auto-approve-renovate
