name: Code2Spaces
on: pull_request
jobs:
  code2spaces:
    runs-on: ubuntu-latest
    container: code2spaces/code2spaces:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./install.sh
      - if: failure()
        timeout-minutes: 3
        uses: mxschmitt/action-tmate@v3
