name: Docker
on: pull_request
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v2
        with:
          repository: ${{ github.repository }}
          dockerfile: .devcontainer/Dockerfile
          push: false
