name: Dotfiles
on: pull_request
jobs:
  dotfiles:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./install.sh
      - if: failure()
        uses: mxschmitt/action-tmate@v2
