name: Dotfiles
on: pull_request
jobs:
  dotfiles:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          exec bash install.sh
      - if: failure()
        timeout-minutes: 3
        uses: mxschmitt/action-tmate@v3
