name: E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  e2e-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: KVM Linux Virtualization
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils cpu-checker
          kvm-ok || echo "KVM acceleration may not be available"
          sudo modprobe kvm
          sudo chmod 666 /dev/kvm
          sudo systemctl start libvirtd
      - name: Setup Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            trusted-users = root runner
            system-features = kvm
            max-jobs = auto
            cores = 0
      - name: Run Install Command
        run: |
          curl -fsSL https://raw.githubusercontent.com/shunkakinoki/dotfiles/${{ github.sha }}/install.sh | sh
        env:
          GITHUB_PR: ${{ github.event.pull_request.number }}
  e2e-check:
    if: always()
    needs:
      - e2e-run
    runs-on: ubuntu-latest
    steps:
      - name: Alls Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
