name: E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Install Command
        run: |
          curl -fsSL https://raw.githubusercontent.com/shunkakinoki/dotfiles/${{ github.sha }}/install.sh | sh
        env:
          GITHUB_SHA: ${{ github.sha }}
