name: Release
on:
  push:
    branches:
      - alpha
      - beta
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: create-pull-request/${GITHUB_REF##*/}
        env:
          HUSKY_SKIP_HOOKS: 1
