name: Semantic
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
jobs:
  semantic-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      pull-requests: read
    steps:
      - name: Semantic PR Title
        uses: amannn/action-semantic-pull-request@v6
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  semantic-check:
    if: always()
    needs:
      - semantic-pr
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Alls Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
